version: '3'

services:
  db:
    image: postgres:9.6.9-alpine
    volumes:
      - db_data:/var/lib/postgresql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '25.000'
          memory: 1024M
        reservations:
          cpus: '25.000'
          memory: 512M
    environment:
      POSTGRES_DB: dev-node
      POSTGRES_USER: node
      POSTGRES_PASSWORD: nodejs
    ports:
      - "5432:5432"
  
  redis:
    image: redis:4.0-alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '25.000'
          memory: 1024M
        reservations:
          cpus: '25.000'
          memory: 512M
    ports:
      - "6379:6379"

  api:
    image: quay.io/perriea/needpc-api:latest
    depends_on:
      - db
      - redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '25.000'
          memory: 512M
        reservations:
          cpus: '25.000'
          memory: 450M
    environment:
      - NODE_ENV=development
      - APP_SESSION_SECRET=RANDOM
      - APP_REDIS_HOST=redis
    ports:
      - "80:8080"

volumes:
    db_data: